version: '3.5'

services:
  api01: &api
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api01
    ports:
      - "8081:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/rinha_db"
    networks:
      - rinha-backend
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "180MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/rinha_db"
    ports:
      - "8082:8000"
    networks:
      - rinha-backend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    networks:
      - rinha-backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "40MB"

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rinha-backend
    command: postgres -c max_connections=300
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "150MB"
#
#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#      PGADMIN_LISTEN_PORT: 5050
#    networks:
#      - rinha-backend
#    depends_on:
#      - db
#    ports:
#      - "5050:5050"
networks:
  rinha-backend:
    driver: bridge